web:
  image: montefuscolo/wordpress

  volumes:
   - ./src:/var/www/html

  environment:
   - WORDPRESS_DB_NAME=povosisolados
   - WORDPRESS_WP_DEBUG=true

  links:
   - db:mysql

  ports:
   - "80:80"

db:
  image: mariadb

  environment:
   - MYSQL_ROOT_PASSWORD=povosisolados_root
   - MYSQL_USER=povosisolados_user
   - MYSQL_PASS=povosisolados_pass
   - MYSQL_DATABASE=povosisolados
