web:
  image: montefuscolo/wordpress
  volumes:
   - ./src/:/var/www/html/
  environment:
   - WORDPRESS_WP_DEBUG=true
  links:
   - db:mysql
  ports:
   - "8000:80"
db:
  image: mariadb
  environment:
   - MYSQL_USER=thewpuser
   - MYSQL_PASSWORD=thewppass
   - MYSQL_DATABASE=wordpress
   - MYSQL_ROOT_PASSWORD=thesuperpass
   - TERM=dumb
  volumes:
   - ./db/boletim.sql:/docker-entrypoint-initdb.d/boletim.sql
